apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-nodejs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-nodejs
  template:
    metadata:
      labels:
        app: app-nodejs
    spec:
      containers:
      - name: appnodejs
        image: haroldo89/demo-ingress-nodejs:8
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
          - name: http-port
            containerPort: 80