# definicion de servicio interno.
apiVersion: v1
kind: Service
metadata:
  name: appnodejs-internal-service
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: appnodejs
