# definicion de servicio interno.
apiVersion: v1
kind: Service
metadata:
  name: appnodejs-nodeport-service
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 32000
  selector:
    app: appnodejs