# definicion de servicio interno.
apiVersion: v1
kind: Service
metadata:
  name: service-internal-nodejs
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 3000
  selector:
    app: app-nodejs
---
apiVersion: v1
kind: Service
metadata:
  name: service-nodeport-nodejs
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 3000
      nodePort: 32000
  selector:
    app: app-nodejs